# Generated by Django 3.0.8 on 2020-08-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
