# Generated by Django 3.0.8 on 2020-08-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
