# Generated by Django 3.0.8 on 2020-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
